[package]
name="quote"
version="0.1.0"
edition="2021"

[dependencies]
regex = "1.10.2"
lazy_static = "1.4.0"

[dev-dependencies]

[lib]
name="quote"
#crate-type=["cdylib", "lib"]
crate-type=["dylib", "lib"]
