[package]
name="quoteparser"
version="0.2.0"
edition="2021"

[features]
default = []
cinterf = []

[dependencies]
regex = "1.10.2"

[dev-dependencies]

[lib]
name="quoteparser"
crate-type=["cdylib", "lib"]